kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
#kubeadmConfigPatches:
#- |
#  apiVersion: kubeadm.k8s.io/v1beta1
#  kind: ClusterConfiguration
#  metadata:
#    name: config
#  networking:
#    serviceSubnet: 10.0.0.0/16
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - containerPath: /hw
    hostPath: /home/tim/Code/spaceship/hw
